<a href="https://colab.research.google.com/github/vaishali28h-crypto/NLP-LAB/blob/main/exp4" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
from google.colab import files
files.upload()

Saving twitter4000.csv to twitter4000.csv

{'twitter4000.csv': b'twitts,sentiment\r\nis bored and wants to watch a movie  any suggestions?,0\r\nback in miami.  waiting to unboard ship ,0\r\n"@misskpey awwww dnt dis brng bak memoriessss,  I thnk I\'m sad. LoL",0\r\nughhh i am so tired  blahhhhhhhhh,0\r\n@mandagoforth me bad! It\'s funny though. Zachary Quinto is only there for a few though.  &amp; to reply just put the @ symbol before the name!,0\r\n"brr, i\'m so cold. at the moment doing my assignment on Huntington\'s Disease, which is really depressing ",0\r\n"@kevinmarquis haha yep but i really need to sleep, i feel like crap lol cant sleep when he\'s away  god i\'m pathetic!",0\r\neating some ice-cream while I try to see @peterfacinelli\'s followers numbre raise...not working sadly ,0\r\n@phatty84 just hella bored at work  lol,0\r\nFood poisoning blowssss ,0\r\n"@StaciG She sent home the best guy, I\'m over the show already ",0\r\n@shika Yeah I did. Trying to recover it now. I guess its time to retire that hardware ,0\r\ncan\'t fall asleep ,0\r\nPadres come back from being down 6-0 &amp; we lost. Breaking the streak!  still loving my padres tho,0\r\nAwe shiiiiiiiiiiiit! Chente got dem killahzzzz............! ,0\r\n@sfannah Ahhhhh  Well at least I\'m up to!,0\r\n@BrianQuest I made 1 fo u 2: http://bit.ly/eId8A  I tried but its kinda ugly cuz I couldnt find pics ,0\r\n"mhm  oh, I brought my hendrick\'s out to vancouver (what\'s left of it), cause I didn\'t want to try tracking some down xP",0\r\n"@garethemery Gareth, all of are tuned, it but they are not broadcasting main stage, which kinda sucks, so we wont get to listen to u ",0\r\n@KimberleyMtkg Hey there! No can do!  Traveling and not back in town until mid next week.    Miss you!,0\r\n"@DanieSass so IDK when it happened or how, but i accidentaly stopped following you  how are you??? how have you been?",0\r\nwhat is up with my hip ,0\r\nBack niggly again today (boo) so couldn\'t train as planned  only 15 days \'til Race for Life!! eeek!,0\r\n"ut oh, I wonder if the RAM on the desktop is starting to go ",0\r\n@HungryDomaine you said &quot;Mermaid for dinner&quot; - I was unsuccessfully witty ,0\r\n"Eeeeep! New Moon is only 172 days away... Actually, that is ages. ",0\r\nMissin the wifeyy like no other ,0\r\n@tommcfly i have a whole in my shoe too ,0\r\ni seem to have lost my bank statement. ,0\r\n"Back from the beach, it\xc3\xaf\xc2\xbf\xc2\xbds been a long time since I last had \xc3\xaf\xc2\xbf\xc2\xbdShvizut Yom Alef\xc3\xaf\xc2\xbf\xc2\xbd  well\xc3\xaf\xc2\xbf\xc2\xbdat least @shirshor is on her way to visit me.",0\r\nhummm.. goodnight twitter .. ending off in an upset state ,0\r\nshit you mister gembul! oh no.. you stole my handphone ,0\r\nis wishing tomorrow will be easier than today but then comes red day ,0\r\ni am so exhausted ,0\r\nWah...I Miss Him So Much  ..,0\r\n"I was rollin\' up Prince Ave, heard all the sirens, looked over and saw lots of smoke. ",0\r\n@jChamanes I\'m not a sir! ,0\r\n"Geography gcse on tuesday and i couldn\'t be more scaredddd, i seriously know i\'m gunna fail and i really don\'t want to. ",0\r\n"Studying, cleaning and grocery shopping, all whilst hungover... what a fun day ",0\r\nInternet still down. Luckily I can watch the game. Sorry if you DM..I can\'t answer ,0\r\n"Ah, suddenly I can feel the bitter of those medicines. ",0\r\nBored at work. I don\'t get outta here \'til 5pm. Bleh. Brewery tonight with my girls. I wish Kristy was here ,0\r\nAnyone want to see transformers tonight? :/ I don\'t want to go alone. too many bugbites ,0\r\n"@andrewhuntre Just looked up The Industry. Looks funny, clever. One review likened it to The Newsroom which I loved! Discontinued tho ",0\r\nstill dont get it !! ,0\r\nI really fucked up this time. I am a moron. Fuck my life. ,0\r\nman i shouldve gone for a cruise what the hell was i thinking coming back home now i\'m bored ,0\r\nHi Matthew how r u my sweet? I miss you   .,0\r\nbaby tell me who is she? ,0\r\n@SonjaCassella Not yet.  Getting some help from my brother &amp; parents this morning. They\'re on their way over.,0\r\n@darenotspeak What\'s wrong?   Did you want to talk about it?,0\r\ni love my nose piercing but its really annoying me right now!  i would hate to take it out ,0\r\n@mamma_J I was spining someone and fell ,0\r\n@Gen215 ROFL following Jesus! Found 1 th othr day had nothin 2 do w God  Jst using His name 2 get traffic 4give them know not what they do,0\r\n@j_kmrprez yeah I want be able to until next year!&quot; ,0\r\n@haemoglobin_ Why? ,0\r\n"@Stedic I work Saturdays, so nope -- I\'m back at work again today. ",0\r\nbattlefield heroes beta site is still down ,0\r\nJust woke up. I was going to go workout but I\'m still sore from Thursday. ,0\r\n@paulmccourt dunno what sky you\'re looking at! loads of clouds &amp; brisk wind in Greenisland ,0\r\n@TwilightofDoom NICE!!!!! I havent seen that movie yet tho.... ,0\r\n@kRaZy_FrEaK495 hows guitar hero? lol and matts gone  idk why...he didnt do anythign i dont think lol,0\r\n"@xxbrry yes, you spell it obituary... why?? sounds sad!  and i have no idea how old he was when he died!! read it like 10 years ago!! xxxx",0\r\n@brianrubin @lomara sorry about the headaches ,0\r\n@KankzXD I am jealous! I love that man! I missed him last time he came to Tassie ,0\r\nhelping my mommy pack . she\'s leaving to Mexico in saturday ! ,0\r\n@anthothemantho hahaha i agree! i cried like a baby when they split the brothers up  ha,0\r\n@antonwheel But you never saw the bees.  Oh the bees. ,0\r\n"@hanaames I\'d like to be lazy but they keep on making me wake up at 7am  But I do get two afternoons off a week, so not quite a job ",0\r\nhafta go get food and then get ready for work  bye @Orla_x,0\r\napparently I have Cats on vinyl. but nothing to play it with ,0\r\n"Lord please don\'t let this guy sit next to me! He got on hi heel boots, a scarf, long nails and ashy hands ",0\r\nI wish I could be back in DC!! ,0\r\n@Bastante_P If only I was in ATL  *sighs*,0\r\ni got heat rash on both feet and am now incapable of walking... damn this weather... (probably the only person in englang thinking that)  ,0\r\nIm back home in Belfast  im realli tired though and upset i aint going to see JLS at the Summertime Ball x,0\r\nOh and if only lens phone didnt die i would know whats going on at the parade ,0\r\n@CatsHateMangos Ah rubbish. I leave for his on 12th ,0\r\nhas used more moisturer today than all the other times of moisturiser usage combined.............. i feel gay ,0\r\n"Got No Txtz,, Itz Cold,, Home Alone And Nothing To Do !!!   ",0\r\n"Dammit, can\'t find a retail outlet round here with the Cruzer Contour ",0\r\n@lilmonkee987 i know what you mean... i feel sorta sad too ,0\r\n@peterfacinelli hey peter just wondering when does nurse jackie air again? i would like to set my dvr to tape it. no iphone here ,0\r\n@marcusjroberts working on a Sunday sucks  don\'t work too hard!,0\r\n@noxertg I saw the wolverine workprint and thought the movie in general sucked. ,0\r\ngoing to london aquarium today! gonna be so hot... ,0\r\n"I\'m heartbroken to say that my grandfather passed away yesterday in the morning at 3:30.  I will miss him so much! I love you, Grandpa.",0\r\n"tomorrow; the last day of school: many tars, many goodbyes, many memories. ",0\r\neurgh my throat is dry! i want a drink ,0\r\n@BeautiFoul i\'m afraid i won\'t have a chance to. i\'m moving back to kansas on tuesday. summer schoolzzzz ,0\r\nPicture isn\'t showing on twitter hmmmmm ,0\r\n"@tracy_nyc I\'m gonna guess &amp; say the final four? Because someone read wikipedia once &amp; assumed I knew who they were, &amp; told me...was sad. ",0\r\n@Kali_roll I miss my ringback tone  but I have that automatic vm lol,0\r\ndoes any1 have the spousal abuse number? I just got hit for my last tweet  lmao,0\r\nnot feeling as great as I did the last time I tweeted...  pity party of one,0\r\nIf only they understood... ,0\r\n I think I\'m starting to get sick... piglet flu?,0\r\nI don\'t really get the whole Twitter thing...I\'m challenged ,0\r\nHeading to work  http://twitpic.com/4eojz,0\r\n@BlondeBlogger http://twitpic.com/4w8hk - I\'m so sad this is so blurry! ,0\r\nTook the boy fishing but no luck so far ,0\r\ni wonder if there\'s a &quot;Crop Circle virus&quot; i can send to my partners farm coz he spends more time in FarmTown than with me. ,0\r\n@Im_Queen on twitterberry... I missed it   whatchu doin up?,0\r\n"@imtalia school is... idk, school. heaps of h/w though  hav u got ur yearlys coming up? xox",0\r\nhello new anipals....Im not feeling the best-I have a swollen bottom lip...must get better soon ,0\r\n@beeyawnkuhh happy berfday!! Sorry i never told you sooner ,0\r\ndoing art while watching season 6 of family guy! should be out in the sun ,0\r\nI always curl my hair when it rains. ,0\r\nWHAT the hell is going on! is NKOTB NOT coming to Australia now ,0\r\n@DopeDiva lolll! i think 2 of my no good followers left me yest  OH WELL ! lol they should kon what theyr gettin in2 when they follow me,0\r\n"@RobbyWat For a minute I thought that said &quot;Maggie has an extra eye growing.&quot;  Yep, I\'m a space cadet.  Sorry for the sweet girl ",0\r\n@NKAirplay i just got a reply from fish &lt;3  yay at least its a band member not unlike a reply from the guys  if i run into you - joe mac,0\r\n"is thinking about spending sometime in the british sun coz got another lovely day, still feeling a bit ",0\r\n@SaraLime Party?  What party?  I was working \'til 8 pm tonight.... ,0\r\n@jsong77  NOT DONE IT\'S ALMOST 2 AM  this youtbe better start acting normaal,0\r\nTime to read legal docs ,0\r\n"twitter, won\'t you allow me to change my photo? ",0\r\n"Thats it, I am going to take a break. I got over 9000 erors ",0\r\ni\'m waiting for my girl to get bk as she fly\'s to CA 2moz and i won\'t see her for 2 months! ,0\r\nI Still got so Many Unsaid Things that I Wanna say... to you ,0\r\n@megpoynter i misss youuu  ima see you tomrrowww (L),0\r\nAwwwww  I wish Britney Spears would follow me on twiter  ,0\r\n@HeyYoBecky I miss dressing up in fun outfits  @PublicEmileNo1 i know.. it is epic,0\r\n@KathiMcFly yep with my two best friends ;DD melli &amp; katie [: but now it\'s over  WAS AWESOME hehe [:,0\r\n"Fuck off, Rafa.  Broken serving for the set?",0\r\n@MasterAwesome 23 almost 24   im an old lady,0\r\nCouldn\'t get moving this morning. Working in the sun everyday is getting to me ,0\r\ntotally shocked at the death of such a good mate ,0\r\nI\'m really stressing now... ,0\r\n@tommcfly Why do you not respond me? ,0\r\ntummy painnnn  boo. this sucks.,0\r\n@madout1 woooooooow nd I wasn\'t there (tear) ,0\r\n"Gray\'s Anatomy Season Finale short-circuited my psyche...power down, retreat into sub-conscious, revisiting ever loss I\'ve ever known ",0\r\n@down_home_kitty Oh balls. I have to go to a wedding &amp; will miss out on the wonderful freebies ,0\r\n@RyanSeacrest im so devastated.  should of been Gokey and Kris. boohoo.,0\r\n"@allissmith haha yeah 2day was 2 B end-o-year fun day stdnt/tchr kickball game, wtrblln toss comp., 5-8th watergun fight but it rained ",0\r\ni wish i still had money so i could buy an owl city t-shirt.  ,0\r\n"@Ladiejay what a day it was  3 hour friends graduation, japanese dining! Shopping now home. I hate graduations ",0\r\n@shaaqT did to whoever was left! think @netra left along with you and @kaushal before that ,0\r\n"@thelithopedion it\'s so weird. Don\'t quite know what it is. I was off yesterday, gonna have to brave it today ",0\r\n"@_tranquilize ill keep you up, i have to stay up for finals again bb ",0\r\n@Rowdyeh its not there anymore ,0\r\nwants to go to the confirmation today but cant  x,0\r\n"@Vinnie_Killgasm ARE YOU EXCITED!!! IM EXCITED!! Not really, cause I\'m not coming ",0\r\nI miss you  \xc3\xa2\xc2\x99\xc2\xab http://blip.fm/~8lc2f,0\r\n"@brianwelburn IT can\'t upgrade to IE8 because much of our software doesn\'t work with it, \'cos that\'s out of date too! ",0\r\nis not v. happy about the rain!!!!!!!!!!!!! it cancelled my rounders match  boohoo,0\r\n"yo, wtf is up with the full &amp; lite view shit on myspace. i hate it ",0\r\n@jmarie7481 Hahahahaha... I know you\'re not. So sad I lost my cd  I think Ray threw it away. I would listen to him everyday.,0\r\n@beacueva dont u know squids can feel it wen u cut em into little rings  EVEN WHEN THEIR DEAD.,0\r\nJust been for a jacuzzi. Now time to pack ,0\r\n@Judius__Maximus i dont want ya to have migraine. ,0\r\n@bagginsboy best part is i\'ve got t4 to watch again tonight ,0\r\n"Ahhh i hate my car now,. time to sell,. Needed to get to an apt at 10 and the battary is dead! ",0\r\nI miss my lappytop. Hope they hurry up with the repairs. ,0\r\n@mcraddictal rofl i\'m not really on my tiran all that often though. No one joins ,0\r\n@katbow  Understandable. Go rent the Star Trek legacy and lock yourself away from it all for the next 11.5 hours. See you Monday.,0\r\nLocked out of my house ,0\r\nSuffering! Pulled a muscle in my chest yesterday and spent the night waking up in agony!! ,0\r\n@MissFredi But I feel so constanly ill  @Davina_Morris,0\r\nIn the vets for Millies\' check up. The cat ain\'t happy. ,0\r\n"@TeenSamantha me too, had to buy new laptop today  Thats my flights to Philly canx now ;)",0\r\nCrowd was insane. Good win... To be honest seemed like SA didn\'t think this through well enough. ,0\r\n@cassendraaa YES YES. UNDERSTAND. ,0\r\njust had to pull glass out of my dogs foot  ew. THANK YOU NEIGHBORS FOR SMASHING BOTTLES IN OUR YARD!!,0\r\nWoo i feel evil today  god forgive me,0\r\ntoday was a great day. really tempted to smoke ,0\r\n"@beschbach You guys and all this stuff, I feel guilty eating egg whites for dinner even ",0\r\nstill waiting for the UPS guy  damn it i want my 360,0\r\n@lolly_poppet: matching socks  im sorry ill be there in like an hour,0\r\n@offirg Sorry but I will be at the Cepic AGM in the afternoon  But maybe you we can chat about it later during Cepic,0\r\nugh!! and the station is full ,0\r\n"Head is splitting again  If I was single last nite I\'d have been knee deep in tang, instead I got the top score in Pacman :0 .... Sad.",0\r\n@likewhoaxox awwz  i hate when that happens!! go drink hot chocolate milk to help you fall asleep lolz,0\r\nohhh 2 write bak 2 ppl u hav 2 put their names 1st evn on ur phone! ughh this whole time i thought i was beastin n im just talkn 2 myself ,0\r\n@JasonLim waaaaa i want ice cream  u\'re so far away la. Come back!,0\r\nMy hair is like a bush ,0\r\n"My cat snuck out, and is stalking somewhere around here lol.  Need to go look for him now     jerk lol.",0\r\n"Watching jonas brothers on MTV, missed the 3d concert at GSC ",0\r\nstudying for exams!  I can\'t wait or summer. 2 more days! :p,0\r\n&quot;test of progress&quot; line in midterm prompt really threw students for a loop. Most wrote about assessment  Lesson for me and them.,0\r\n@charades oh man sounds like work is not fun for you ,0\r\n@dana_ma I\'m from Louisiana originally - I know what you\'re talking about   That\'s one huge reason Ieft the state,0\r\nPhoto: miss germany  http://tumblr.com/xf825f012,0\r\n@megsi23 @PatsyTravers voting is working now but we are soooi behind ,0\r\nI don\'t know what happened... there were some sad penguins on the ice tonight ,0\r\ncatching up on some tv. i miss dvr ,0\r\nNeed some help ,0\r\njust getin home frm work sad and touching I know! smh ,0\r\nOop 3g please dont fail me now ,0\r\nim veryy bad ,0\r\n@DJASAP who is @lil214....lili homie...LILI.... and i am black  75% to be exact lol,0\r\n@gkelly Work prevented me from attending awesome. ,0\r\n; i miss family guyyy. ,0\r\n@Dozeymagz Sorry to break that to you ,0\r\ntrying to figure out tweetdeck and failing miserably  ,0\r\nA lot better. Just realized something though. And its hard. Its one of the hardest things I have ever had to do. ,0\r\nWow 20 days...... Well I can\'t blame me for not having interwebz      ,0\r\nis sad ,0\r\nOut on money match of wsop $10k hu Td9d All-in vs A4 on a 2d3d5 flop. I thought he was making a 3-bet bluff. Not patient enough    ,0\r\n@Alicia_vintage its quite a long story i shouldnt of tweeted that sorry ,0\r\nNot a good run today ,0\r\n@PennyParnevik i m asking myself the same question! But no answers ,0\r\ngonna spend mother\'s day in crawl space and garage moving everything from external walls for termite treatment tomorrow.  cobwebs. ick. ,0\r\n@sross4 why? ,0\r\n@charbrum don\'t deliver at weekends  @nickbev can place an order for you too and then take it to you for your tea ;),0\r\n i juss wish hed talk...,0\r\nfound out i have a throat infection ,0\r\n@COD24 when am i gonna see you? ,0\r\n"AT&amp;T: &quot;you have 4 bars of 3G. oh wait, you want to download something? make that 1 bar of E.&quot; rinse/repeat. thx. ",0\r\n@RichieSosa Me too ,0\r\nI have a rip in my pants. I knew I felt a draft earlier ,0\r\nMONDAY + FIRST OF THE MONTH = LONGGGG DAYYYYY. ,0\r\n@Ana_xo ( awww yes take it  I wanna see them.,0\r\n"my eye keeps twitching, lack of sleep ",0\r\nAww man! The Space Shuttle Endeavour launch was scrubbed again. ,0\r\n@nickonken Pandora does not work in Brasil!!! ,0\r\n@_MAXWELL_  What happened to your planned Orlando stop?    Gotta rearrange schedule now...can\'t miss tour!!!,0\r\nis amazed that it\'s already 12am ,0\r\nMorning. Feeling green around the gills this morning ,0\r\n"@vishuxpert he he he.... sorry cant help you on that..... I, myself dont know marathi.... ",0\r\n"Rain, Rain, GO AWAY!  So done with all the wet weather ... Momma needs some Sunshine Therapy.  Even my flip flop tan is fading ",0\r\nummmmm...i\'ve done like nothing all day...what a waste ,0\r\n"@archiwiz Babe, I dunno what blogger has done with my blog roll oo! The whole thing has disappeared.  ",0\r\nat work ,0\r\n"Already sent two or three one-forties without hashtags. I\'m failing miserably on today\'s #140Sunday  Oh, well, oh, well, oh, well. Filler.",0\r\n"I guess I will try to go to sleep now even though I havent heard from @DonnieWahlberg  Oh well, Twugs, Twisses, Goodnite &amp; Sweet Dreams!",0\r\n6\'oclock needs to hurry up. Im not even suppose to be working weekends ,0\r\nI dont know what to do anymore...this is out of fuckin control. ,0\r\n@Glasgowlassy lol aw your fum must be killin ya!! Bet you didn\'t want to go to work today? ,0\r\n@rustyrockets I\'m dancing due to &quot;wolf spiders&quot; taking over my apartment and quite frankly there is nothing good about it. they\'re scary ,0\r\n@NDeWitz thats always a scary realization ,0\r\n"@mawbooks Unfortunately, I\'m finishing some house stuff, no blog stuff. Wasn\'t feeling motivated to start on stuff at 10pm. ",0\r\nGays aren\'t supposed to be fat.  LOL!  http://twitpic.com/6uvgi,0\r\nOut getting ice creamm!!... So tired ,0\r\nhave my permit test in the morning im so scared that im gonna fail ,0\r\n no voodoo. But i met a really cool person that was at the bus stop. Lol,0\r\n"Alex\'s mum insists getting up and walking around is the best thing for me, but the pain is *so* bad when I get up  bored silly in bed tho",0\r\n"Morning! Just woke up. Bit early, but I couldn\'t sleep anymore  Going to learn English a bit. Yes, I can do that on the computer!",0\r\n"@Maiybe I\'m sorry  I really wish I could have made it, but there was no way. I didn\'t get to do anything I wanted today.",0\r\n"@itschristablack i know it would be awesome, i wish yall come back to puerto rico ",0\r\ndave hates my tweets. ,0\r\nHad to take a sick day ,0\r\nInternet is getting damn slow today.. ,0\r\noh. my. actual. god. i just picked up a spider thinking it was some piece of string. how disgusting?! ,0\r\nI have like 3 mosquitos on my neck ,0\r\n"@halbpro Dude, I feel for you. In this heat. ",0\r\n@Laird_Attwood sorry sorry sorry  if you like i could hop on train to crewe to bring phone/wallet?,0\r\n"could not ride yesterday..    of course, today, there is a wonderful sun!!! argh!",0\r\n"@TheMightyFoz From that Tweet, the link went to the picture in que

In [ ]:
data = pd.read_csv('/content/twitter4000.csv')

In [ ]:
pattern = r'\w+@\w+.\w+'

In [ ]:
data['twitts'].apply(lambda x:re.findall(pattern=pattern, string=x))

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
data['email'] = data['twitts'].apply

In [ ]:
pattern = r'\b[A-Za-z._+-]+@[A-Za-z.].[A-Z|a-z]{2,}\b'

In [ ]:
data

,twitts,sentiment,email
0,is bored and wants to watch a movie any sugge...,0,<bound method Series.apply of 0 is bored...
1,back in miami. waiting to unboard ship,0,<bound method Series.apply of 0 is bored...
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,<bound method Series.apply of 0 is bored...
3,ughhh i am so tired blahhhhhhhhh,0,<bound method Series.apply of 0 is bored...
4,@mandagoforth me bad! It's funny though. Zacha...,0,<bound method Series.apply of 0 is bored...
...,...,...,...
3995,i just graduated,1,<bound method Series.apply of 0 is bored...
3996,Templating works; it all has to be done,1,<bound method Series.apply of 0 is bored...
3997,mommy just brought me starbucks,1,<bound method Series.apply of 0 is bored...
3998,@omarepps watching you on a House re-run...lov...,1,<bound method Series.apply of 0 is bored...
3999,Thanks for trying to make me smile I'll make y...,1,<bound method Series.apply of 0 is bored...

In [ ]:
pattern = r'https\s+|www\s+'

In [ ]:
data

,twitts,sentiment,email,email_count
0,is bored and wants to watch a movie any sugge...,0,,1
1,back in miami. waiting to unboard ship,0,,1
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,,2
3,ughhh i am so tired blahhhhhhhhh,0,,1
4,@mandagoforth me bad! It's funny though. Zacha...,0,,1
...,...,...,...,...
3995,i just graduated,1,,1
3996,Templating works; it all has to be done,1,,1
3997,mommy just brought me starbucks,1,,1
3998,@omarepps watching you on a House re-run...lov...,1,,1
3999,Thanks for trying to make me smile I'll make y...,1,,1

In [ ]:
pattern = r'\b[A-Za-z0-9._%+-]+@[A-ZA_Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
data['email'] = data['twitts'].apply(lambda x: "," .join(re.findall(pattern=pattern, string=x)))
data['email_count'] = data['twitts'].apply(lambda x:x.count(',')+1 if len(x)>0 else 0)

In [ ]:
data.head()

,twitts,sentiment,email,email_count
0,is bored and wants to watch a movie any sugge...,0,,1
1,back in miami. waiting to unboard ship,0,,1
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,,2
3,ughhh i am so tired blahhhhhhhhh,0,,1
4,@mandagoforth me bad! It's funny though. Zacha...,0,,1